### ISSUE TITLE
Connection dropping on freenode is problematic

### ISSUE THREAD

**Issue by equwal** [matrix-org/matrix-appservice-irc#1008]
LdBeth is a matrix user and regular on freenode's `#lisp` channel. He was blocked by the connection limit, it seems.

We at `#lisp` suggest you add a way for individuals to host freenode users from matrix with the ports on their servers, so that there are more than 2^16 connections (ports) to choose from. Allow for load balancing across these volunteers. This way, LdBeth would have had a connection to use on 2020-03-15 in the `#lisp` channel.

I'm not clear if I fully understand the details of why LdBeth was not able to post on #lisp on 2020-03-15, so please let me know if there are other considerations.

# Acknowledgement
Many thanks to `no-defun-allowed` for her help in understanding this issue.

**Comment by Half-Shot** [comment]
So there are several things at play here. I'm not sure why the user wasn't allowed to talk in the channel (and I will need a mxid to investigate). We have kept under the limit for the matrix.org bridge by running the kick script, so everybody should be able to talk.

In terms of trying to load balance, there are reasons why we can't:
- matrix.org is not limited by ports and even if we were, we are hosting far less than `2^16` users.
- we are limited by freenode not wishing to provide us more connection slots.

Trying to crowdsource more connection slots is problematic because:
- First off, it would be an enormous undertaking to support this kind of behaviour in the bridge, having to delegate to a unknown third party. The risk of security issues is too great. For instance, we use these connections for not just outbound messages, but seeing inbound messagess too.
- If the user's external service goes down, then what?
- Freenode require us to deliver all messages both ways with as much reliability as possible. If we externalize in the way described, we wouldn't be able to guarantee that.

The best I can really offer folks is an easy way to reconnect to the bridge if they are unable to connect or are kicked for being idle. The other thing we can do is try to make the idleness algorithm more fair, but it's not an easy feat.

**Comment by equwal** [comment]
> The best I can really offer folks is an easy way to reconnect to the bridge if they are unable to connect or are kicked for being idle. 

This would be helpful, if that is the true cause of this issue.

> The other thing we can do is try to make the idleness algorithm more fair, but it's not an easy feat.

**Comment by LdBeth** [comment]
I'm the person having this issue and today after tried to reconnect the bridge I find that it's because `#lisp` requires the nickname to be identified via NickServ to join the channel. I did setup the nickname password via the `!storepass` but it seems the identification message wasn't sent to NickServ after reconnected from idle.
