### ISSUE TITLE
Unable to bridge large room between matrix.org and OFTC

### ISSUE THREAD

**Issue by FedericoCeratto** [matrix-org/matrix-appservice-irc#1100]
Hello,
I'm trying to enable bridging between the Mobian room on matrix.org and #mobian on OFTC and it fails with:
`Failed to make link: This room has 315 users, but the maximum for a bridged room is 100.`

Other large rooms seem to be working, and I don't see hints on the FAQ on what to do.
Any help? Thanks

**Comment by Half-Shot** [comment]
Hey, this is by design because our IRC bridges have a limited number of connection slots. To stop people from potentially using up all our connection slots, we set a limit at bridging more than 100 users. If you have a special case such as being a project maintainer and need to bridge, contact me on @Half-Shot:half-shot.uk

**Comment by Half-Shot** [comment]
(solved via PM)
