### ISSUE TITLE
The bridge will send url with spaces on it for pasted images

### ISSUE THREAD

**Issue by necessarily-equal** [matrix-org/matrix-appservice-irc#1219]
**Describe the bug**
When pasting an image with spaces in it, IRC will see something like this:
> \* nick uploaded an image: Screenshot from 2021-01-11 19-03-08.png (332KiB) < https://matrix.org/_matrix/media/r0/download/gnugen.ch/eIgbEuqYFfYzZuWeKqllgKlJ/Screenshot from 2021-01-11 19-03-08.png >

**To Reproduce**
* join an IRC channel (both from Matrix and IRC)
* send a picture with spaces in the name
* admire how the link isn't clickable on IRC

**Expected behavior**
The URL is URL-encoded.

**Comment by andrewshadura** [comment]
How about *also* drastically shortening it? Right now, the name is repeated twice; it also seems the id is just enough for the link to work, e.g. https://matrix.org/_matrix/media/r0/download/gnugen.ch/eIgbEuqYFfYzZuWeKqllgKlJ/ is still fine. `<>` could also be removed since they add no value. I’ve also had people complain about "uploaded an image", but maybe that could be kept.
So, how about:
```
 * nick uploaded an image: https://matrix.org/_matrix/media/r0/download/gnugen.ch/eIgbEuqYFfYzZuWeKqllgKlJ/
```

**Comment by andrewshadura** [comment]
Well, this PR doesn’t address the comment about shortening the link.

**Comment by andrewshadura** [comment]
Should I open a separate issue?

**Comment by necessarily-equal** [comment]
Most likely yes, otherwise it will just be forgotten.
