### ISSUE TITLE
Changing registration sender_localpart disallows connection to HS admin room

### ISSUE THREAD

**Issue by lukebarnard1** [matrix-org/matrix-appservice-irc#124]
After setting up registration to a HS, changing the sender_localpart of the registration file (or generating a new registration file with a different argument to the `-l` option, which sets sender_localpart) will prevent the new bot from connecting to the HS admin room.

**Comment by Kegsay** [comment]
Not sure what we can do about this. A different sender_localpart means that the AS bot is actually an entirely different user. Admin rooms are invite only, and the bridge has no way to invite itself into the room (since it can no longer puppet the old sender_localpart). This feels like a PEBKAC which we cannot guard against sadly. Closing.
