### ISSUE TITLE
Shorten up the text for pasted images

### ISSUE THREAD

**Issue by andrewshadura** [matrix-org/matrix-appservice-irc#1243]
It would be great if the text could be shortened to the absolute minimum. Before PR #1237, the name was repeated twice; it also seems the id is just enough for the link to work, e.g. https://matrix.org/_matrix/media/r0/download/gnugen.ch/eIgbEuqYFfYzZuWeKqllgKlJ/ is still fine. `<>` could also be removed since they add no value. I’ve also had people complain about "uploaded an image", but maybe that could be kept.
So, how about:
```
 * nick uploaded an image: https://matrix.org/_matrix/media/r0/download/gnugen.ch/eIgbEuqYFfYzZuWeKqllgKlJ/
```

_Originally posted by @andrewshadura in https://github.com/matrix-org/matrix-appservice-irc/issues/1219#issuecomment-770034722_

**Comment by Half-Shot** [comment]
The filename was added recently, because otherwise the browser would download files as "eIgbEuqYFfYzZuWeKqllgKlJ" and in some cases just fail to render properly at all. We're going to keep the filename because:

1) It does solve a problem (ref: https://github.com/matrix-org/matrix-appservice-irc/issues/1085)
2) It's not actually duplicating any information.

I recognise the need to save on characters here, but I think we're really talking a few bytes here or there.

**Comment by andrewshadura** [comment]
I’m afraid you’ve misunderstood the nature of the complaint.
People on IRC complain that people from Matrix spam IRC. I’m not about counting bytes, it’s about posting too long messages with too long links. People get annoyed, people start hating Matrix and being angry at people using it.
I think that bridging IRC and Matrix should be as frictionless as possible. Having excessively long messages goes against that goal.
