### ISSUE TITLE
How to update the configuration/registration

### ISSUE THREAD

**Issue by piegamesde** [matrix-org/matrix-appservice-irc#1244]
**Is your feature request related to a problem? Please describe.**
When updating the config.yml, it may come out of sync with the registration file. What is the best way to manage this case? I suppose that re-generating the registration file will reset all tokens, which may be bad?

**Describe the solution you'd like**
Maybe have a flag to update the registration file based on an existing one

**Describe alternatives you've considered**
Maybe having a different ID and tokens after every change is fine

**Additional context**
I'm working on https://github.com/NixOS/nixpkgs/pull/95854.

**Comment by Half-Shot** [comment]
You need to keep the same ID between restarts otherwise synapse will be confused.
The tokens can change if synapse is also restarted. 

I'm assuming the reason that you are worried about this is because you have special requirements regarding Nix? The only time you'd need to change your registration file is if you wanted to change the user or alias format, and so need to update the namespace area of the config. If so, I'd suggest somehow retaining those tokens in memory and copying them to the new file manually.

The registration file generation command is only meant to be used for first setup, and afterwards users should maintain the file themselves.

**Comment by piegamesde** [comment]
Yes, my use case for this was that I added an IRC server to the bridge (with a custom namespace), and then got confused because the registration.yml was still showing the old value.

> The registration file generation command is only meant to be used for first setup, and afterwards users should maintain the file themselves.

Thanks for the information. I now do this by regenerating the registration file every time, and then fixing up the tokens [using grep+sed](https://github.com/NixOS/nixpkgs/pull/113988/commits/e16039143d48c4e9063012fd967fdbc58cb009a0#diff-b52aaee84e22c73570a0663f15609885b40b112088cbe191a5ca1e1f859e0dd5R149-R166). I am going to close this issue, but an upstream CLI flag that does this for me would be greatly appreciated.

**Comment by Half-Shot** [comment]
Sure. I'll create an issue for you on the relevant project :+1:

**Comment by Half-Shot** [comment]
https://github.com/matrix-org/matrix-appservice-bridge/issues/309

**Comment by piegamesde** [comment]
Oh, I didn't know that code came from another project. Many thanks!
