### ISSUE TITLE
Docs: +b and +r mode are in the headline but not explained in the text

### ISSUE THREAD

**Issue by jaller94** [matrix-org/matrix-appservice-irc#1252]
It would be good to explain the `+b` and `+r` mode, which are mentioned in the headline.
What do they do? How do they affect Matrix users? Is the bridge able to handle them?

https://github.com/matrix-org/matrix-appservice-irc/blob/develop/docs/irc_modes.md#bans-invite-only-and-registered-only-b--i--r

Also, these modes are case-insensitive, right?

**Comment by Half-Shot** [comment]
>The IRC bridge will kick a Matrix user on join if they are not able to join the IRC channel. This means if the IRC user is banned, the room is invite only (and the user has not been invited) or the channel is registered only then the user will not be able to join it.

I think that summaries fairly well that these 3 modes will cause the Matrix users to be kicked. I've deliberately not explained the modes themselves because:

1) The bridges does NOT handle the modes, it handles the error responses from failing to join a room which is a difference here.
2) The documentation is not here to explain IRC modes, but how the bridge handles cases around them. I.e. it's not for us to explain how a ban works which is actually specific to the ircd/network to some extent, but how the bridge handles the failures.

I only included the mode names because it's easy to parse that adding `+b matrixuser` to a room would cause the user to be kicked on join, but in reality the bridge doesn't use the modes themselves.
