### ISSUE TITLE
Nicknames with asterisks (*) appear as undefined at Matrix (CTCPs from undefined are broken too) / ROLEPLAY are broken

### ISSUE THREAD

**Issue by Mikaela** [matrix-org/matrix-appservice-irc#1422]
**Describe the bug**

Said in the title, practically #712 and #1411, except ROLEPLAY is borderline deprecated while not going to be removed from codebase.

**To Reproduce**
1. Go to room with roleplay enabled (mode +E) on a server with ROLEYPLAY enabled
2. Send `NPC #channel whoever whatever` or `NPCA #channel whoever does whatever`
3. Observe nicks who should be *whoever* being unknown instead

**Expected behavior**

The nickname appears properly

Edit: adding keyword Ergo IRCd

**Comment by emersonveenstra** [comment]
This is also https://github.com/matrix-org/node-irc/pull/81, but there's more of a chance that a lot of stuff could blow up because the mxid spec says "For example, "*" is used as a wildcard in some APIs (notably the filter API), so it cannot be a legal user ID character." synapse will accept it, but we might need to encode the asterisks somehow
