### ISSUE TITLE
Messages from libera.chat are not shown in a room with other bridges

### ISSUE THREAD

**Issue by rcurtin** [matrix-org/matrix-appservice-irc#1445]
First of all, thank you so much to the project contributors and maintainers.  Our project (github.com/mlpack/mlpack) runs its chat infrastructure on Matrix and all of the bridges are wonderful, as they let our users use their preferred mode of communication.

**Describe the bug**

Recently we bridged `#mlpack:matrix.org` into `#mlpack` on irc.libera.chat.  However, it seems that messages from irc.libera.chat are not always sent to `#mlpack:matrix.org`.

Fascinatingly, we did observe one user who came into the libera.chat room (to set up a logging system, on whitequark.org) and their messages were sent to Matrix.  But, other libera.chat users' messages are not sent to Matrix, and it's not clear why.  We've tried with different non-colliding usernames.

`support@matrix.org` suggested that this could be a manifestation of #1209, but I'm not entirely sure if that applies in this case.

**To Reproduce**
1. Join `#mlpack:matrix.org`.
2. Also fire up an IRC client and join `#mlpack` on libera.chat.
3. Send a message
4. Don't see message in Matrix

**Desktop (please complete the following information):**
 - OS: Debian (though my personal OS probably does not make the difference here)
 - Browser: Firefox
 - Version: 78.11.0esr

**Smartphone (please complete the following information):**
 - Device: Pixel 4a 5G  (also probably does not make the difference here)
 - OS: LineageOS :smile:
 - I'm using the Element app

Thanks so much for any help! :+1:

**Comment by Half-Shot** [comment]
So the messages are missing because the room is a victim of https://matrix-org.github.io/matrix-appservice-irc/latest/administrators_guide.html#enforcing-matrix-users-to-be-connected-to-irc (something Libera require the bridge to do).

I believe the room is bridged to a bunch of Slack users, which under the present system cannot be calculated to be unique as a username must be <= 10 chars, and slack users are in the format of `_slack_12345679`.

I've written a PR #1446, which will stop us trying to create unique usernames for users on IPv6 enabled bridges (like libera) because it's not required if the IP address is also unique.

**Comment by Half-Shot** [comment]
(This will be released in the coming days)

**Comment by rcurtin** [comment]
Thanks!  How can I track when a release happens, so I can test the functionality?
