### ISSUE TITLE
Events are sometimes delivered out of order

### ISSUE THREAD

**Issue by Ralith** [matrix-org/matrix-appservice-irc#145]
This is easily reproduced on my instance of the bridge when a user interacts with an IRC bot: frequently, the bot's response will arrive before the user's message. In the case of a greeter bot, often a user's greeting is displayed before the user even joins the channel.

To avoid this, and potentially deeper issues as more IRC-side state gets bridged, the bridge should take care to deliver events to matrix in exactly the order they were received from the IRC server, by queuing bridged events and not beginning to transmit event n+1 until event n has been successfully delivered.

**Comment by Kegsay** [comment]
The bridge currently queues up events sent from the same user. Bot interaction is a fun one because the response is sent by a different user. This means the response can race if the user who sent the command is a bit slow to send to Matrix (rate limiting timers are per user on Matrix).

We will need to add another layer of queueing: a per-room queue, which will be able to keep causality in check. This may have unfortunate side effects. If a user has just triggered rate limiting, then begins to talk in a different room, that room is then at the mercy at the rate-limiting timer for that user. This means it is possible for the bridge to fall quite badly behind on high-traffic channels.

We may be able to mitigate against this by adding in some heuristics on the queue: if the queue builds up too much then ignore causality and flush the queue asap: but this then is even worse than what we have currently, since peoples general chatter will be racing with each other rather than the more obvious request-response nature of a bot.

These are some of the reasons why the bridge currently does not do per-room queues. The issue is valid though so I will leave this open in case there are some good alternative solutions.

**Comment by Ralith** [comment]
Would it make more sense for synapse to (optionally?) not rate-limit (or at least have a very high rate limit for) users generated by an application service? Since someone capable of installing an application service is necessarily authorized to configure/modify synapse itself, this seems like a reasonable feature, and it sounds like it would drastically reduce the complexity needed here.

**Comment by Kegsay** [comment]
It would help, but the idea of connections taking a long time to complete are not limited to rate limiting. We still need to work out what the bridge should do if say, a connection has to wait for TCP-level timeouts to kick in. Do we stop waiting before then? If yes, then what do we do? If not, then we risk locking up entire channels for many minutes at the slightest blip of connectivity.

**Comment by Ralith** [comment]
Under what circumstance does a slight blip in connectivity cause a complete TCP timeout?

**Comment by Ralith** [comment]
It looks like IRC PART/QUIT events are delivered out-of-order with regard to actual messages, even from the same user, which can result in messages being lost entirely.

**Comment by Kegsay** [comment]
Hmm, that shouldn't happen since we [explicitly](https://github.com/matrix-org/matrix-appservice-bridge/blob/master/lib/components/intent.js#L252) try to re-join the room if we [fail to send the message](https://github.com/matrix-org/matrix-appservice-bridge/blob/master/lib/components/intent.js#L503).

**Comment by sbts** [comment]
@Kegsay it seems I'm seeing a related issue over the last month or so.
Commonly people (IRC side) that Join and Post immediately have their first post dropped as the `@user joined @room` message seems to need to arrive BEFORE their first post

I assume that behind the scenes an IRC user's post can't be delivered unless they are a member of the room, and that the join is happening faster than their first post.

**Comment by Half-Shot** [comment]
This **should** be finally somewhat improved by #952, where messages are enqueued *before* `IrcHandler` (nearly, after being filtered by `IrcEventBroker`). Messages will still be sent out of order if a message takes a very long time to send, but this should be fine in most cases.
