### ISSUE TITLE
 have a separate setting for internal/external URL

### ISSUE THREAD

**Issue by rubo77** [matrix-org/matrix-appservice-irc#154]
If you upload an image, it uses the homeserver url for the IRC side of it, which makes sense until that is "localhost:8008" :/

**Comment by rubo77** [comment]
lukeb suggests to add a new item into `config.yaml`, which is an option that allows for an alternative URL for media downloads 
(something like `media_url`) 
Then you'll need to thread this through the code until it reaches here : https://github.com/matrix-org/matrix-appservice-irc/blob/master/lib/models/MatrixAction.js#L48 at which point you can use `getHttpUriForMxc(media_url, event.content.url)` instead of what is already there

You will also need to require `getHttpUriForMxc` from the package it is within (which is ContentRepo of require('matrix-js-sdk'))
https://github.com/matrix-org/matrix-js-sdk/blob/d9318a60e41578674ff900d2c77b4bb39dff88fe/lib/content-repo.js#L37

If `media_url` is not provided, it should just fall back onto the HS URL

**Comment by Mikaela** [comment]
This issue possibly includes matrix.org using http for media URLs instead of https? 

It looks like HTTPS Everywhere has a rule for Matrix.org, but that only protects HTTPS Everywhere users and even having HSTS (which matrix.org doesn't have) wouldn't protect smaller browsers that don't have HSTS preload list if they never accessed matrix.org over https which is less likely with all media links being http.
