### ISSUE TITLE
Room visibility setting is broken for appservice directories

### ISSUE THREAD

**Issue by Half-Shot** [matrix-org/matrix-appservice-irc#1606]
The bridge is trying to set the visibility of a room to its network name -_-

```
122022-09-13 08:42:28 INFO:IrcBridge [-] PUT http://localhost:8008/_matrix/client/r0/directory/list/appservice/!ulpzbqqkOSdqWjdtrb%3Abeefy/public (AS) Body: "{\"visibility\":\"localhost\"}"
```

**Comment by jaller94** [comment]
Function in the bridge looks good.
Function in matrix-appservice-bridge looks good.

Somehow the parameters must get mixed up.

* Instead of a network, the URL contains the roomId.
* Instead of a roomId, the URL contains the visibility.
* Instead of a visibility, the URL contains the network.


The URL should be `/directory/list/appservice/<network>/<roomId>`.

**Comment by jaller94** [comment]
I guess this was fixed in https://github.com/matrix-org/matrix-appservice-bridge/commit/5dd1c4f6e123ba83238da9e4995c88239256cd50#diff-b245d4e56ebec789c8b9d861c90f44e7d635f293b3928c587d42f36cc4cec7a6L856 of the matrix-appservice-bridge.

The former call parameter order does not match the function parameter order of matrix-js-sdk.

* https://github.com/matrix-org/matrix-appservice-bridge/blob/bfc1a0e7b5f5b5de94f03c7eba1edbdb55896327/src/components/intent.ts#L856
* https://github.com/matrix-org/matrix-js-sdk/blob/caadc6f95b357ef5ec203f09e89b4190dd9a45c6/src/client.ts#L7793-L7796

Tasks:
* [ ] matrix-appservice-bridge must be upgraded from ^3.2.0 to ^5.0.0
