### ISSUE TITLE
creating Matrix->IRC PMs on the Libera bridge is broken

### ISSUE THREAD

**Issue by progval** [matrix-org/matrix-appservice-irc#1687]
1. send a message from Matrix to an IRC user on Libera
2. (wait a few seconds)
3. notice the IRC user joined
4. (wait)
5. (the message is not sent)
6. make the IRC user send a message
7. the message is received on Matrix (in the same PM room)
8. then, the Matrix user can reply

This happens with Matrix users both on matrix.org and on other homeservers.

This is not caused by user modes on Libera (`+g` or `+R`).

**Comment by Half-Shot** [comment]
When testing this in Element, all that I managed to prove is that it creates encrypted DMs with bridged users which is definitely trouble. However, that kinda makes me unable to test the actual bug this is reporting.

**Comment by Half-Shot** [comment]
Having looked at this it does seem to work for me. It's slow in a lot of areas though:

- Federation delays means invites takes a few seconds for me, and I suspect it's non-obvious that the Matrix user is getting connected behind the scenes.
- All the messages I sent since the bot joined did work, so I think this is actually working for me.
