### ISSUE TITLE
Provisioning breaks badly when the AS bot is rate limited

### ISSUE THREAD

**Issue by Kegsay** [matrix-org/matrix-appservice-irc#199]
If the bridge Matrix bot gets an invite and the join gets rate-limited:
 - People can't re-invite to nudge the bridge into action.
 - People cannot kick the bot because the provisioning process gives the bot 100% power.

This sucks.

**Comment by lukebarnard1** [comment]
OK, upon investigation, other things break - not just bot joins - when the bot gets rate limited. The ```retry_after_ms``` can be used to try and join the room later. This works so long as the promise to join is defered for 10s of seconds, say a minute. 

But other things fail due to rate limiting, like checking the state of the room, even if the bot has joined by waiting a long time to cool down a bit. My question is why aren't all of these events being scheduled
