### ISSUE TITLE
Some +i rooms (e.g. ##sjw on FN) don't synchronise invite-only joinrules into Matrix

### ISSUE THREAD

**Issue by ara4n** [matrix-org/matrix-appservice-irc#211]

**Comment by lukebarnard1** [comment]
I think #216 fixes this but it still needs to be confirmed

**Comment by ara4n** [comment]
hm, why would #216 fix this? the problem here was that for some reason the portal room in Matrix for ##sjw had `m.room.join_rules` of `public` rather than `invite`, which completely confuses me given the IRC channel has always been `+i` to my knowledge.  Trying to test it against ##invitetesting on freenode, the `+i` is correctly mapped.

I'm confused.

**Comment by lukebarnard1** [comment]
Actually, that PR was not enough to totally fix this problem, but I'm working on something else that will synchronise join rules when the frontier user joins the IRC channel (whenever that may be). From then on, join rules will be tracked as before (which is what happened with ##invitetesting). 

#219 should fix this, I just need to reduce the number of "MODE" commands sent, because currently it works but it sends one anytime any client joins an IRC channel.

**Comment by Kegsay** [comment]
I have reasonable confidence that https://github.com/matrix-org/matrix-appservice-irc/pull/225 fixes this issue.

Previously, the bridge would only ever sync *changes* to `+i` or `+k`, as received by mode changes. It would not check the **current status** of `+ik` in a channel by explicitly requesting a `MODE #channel`. We now *explicitly* request the mode and then run the same locking semantics, which retrospectively fixes this issue and should in the future too. I've seen evidence of this working when I was tailing the logs, so I believe this issue is now resolved.

Please reopen if you have evidence to the contrary.

**Comment by Fuchs** [comment]
This seems to break invite exceptions (+I) on at least freenode (probably others, too). 
It only checks if a channel is +i and disallows joining it, even if the user would be allowed to due to an invex. 

This is a bit meh, as quite a lot of project internal channels are set +i but grant +I $a:account to their members (which can't be checked without having +o on that channel). 

A proper fix for that issue would be to attempt to join a channel and do so if possible. If the ircd doesn't allow the join, consider further checks (e.g. +i) and tell the user that this might be a possible cause.
