### ISSUE TITLE
Kick inactive Users

### ISSUE THREAD

**Issue by rubo77** [matrix-org/matrix-appservice-irc#284]
In some rooms with hundreds of users it would be useful if there would be an option to kick all inactive Users at were inactive for more than three months

**Comment by rubo77** [comment]
At least Guest Accounts should be Kicked Afte a certain time

**Comment by Kegsay** [comment]
Added `needs-spec` as there is currently no way for a bridge to tell when a Matrix account was last used.

**Comment by rubo77** [comment]
What if I just Kick all IRC Users at midnight?

**Comment by Kegsay** [comment]
Oh you mean IRC users on Matrix?

**Comment by rubo77** [comment]
Yes, in a bridged room, I think I could kick all irc users, because they will rejoin again once a user is active again.

**Comment by Mikaela** [comment]
How would everyone at #bigchannel being kicked at 00:00Z look like to Matrix users? Won't it be blocked by https://github.com/vector-im/vector-web/issues/349 just like https://github.com/matrix-org/matrix-appservice-irc/issues/222 which is the proper solution?

Otherwise I guess it could work as a workaround maybe at least for the guest/unregistered accounts as long as they don't come as guests near midnight.

*I assume that midnight is the UTC midnight or there is a mess?*

**Comment by Kegsay** [comment]
To non guests on matrix there would be a flood of kicks (if the bridge bot has permission to kick). To the guests on matrix, they would get kicked from the room. If it's a manual process then collapsing joins or parts is less of a concern as it's unlikely to occur when people are actively talking. 

@rubo77 yes you can kick them. Yes they will rejoin if they rejoin on the matrix side.

**Comment by Kegsay** [comment]
Agreed.
