### ISSUE TITLE
When pastebinning long messages, (optionally) use the rich-text form

### ISSUE THREAD

**Issue by eternaleye** [matrix-org/matrix-appservice-irc#291]
https://github.com/matrix-org/matrix-appservice-irc/issues/258#issuecomment-263112762 points out that, for the specific use case of long code-bearing messages sent to IRC, the uploaded long message is significantly suboptimal compared to the usual pastebins.

Syntax highlighting was specifically called out, but (presuming the users are properly marking their code fragments) it may be best to simply use the HTML rich-text form, as it's already annotated with code blocks and (possibly) the type of code.

(Note that care should be taken to avoid the bug Vector/Riot has, where the syntax hilighter ignores type flags even when present).

**Comment by Kegsay** [comment]
I have no real desire to implement this. I feel this way because the Matrix user is effectively sending Markdown (human-readable plaintext with a rendered version for savvy clients). If the Matrix user were on an IRC client, they would have the same behaviour when sending the message (albeit not as a pastebin link, but as many IRC messages).

How would an IRC user send the same block of code with syntax highlighting? Manually go to the site, paste it in and send the link, right? Nothing stops the Matrix user from doing the same. I sympathise that it's non-obvious that the IRC user doesn't see wonderfully marked-up code, but I'm not willing to feature creep into designing rich text editors.
