### ISSUE TITLE
After a big outage we should drop history on the floor

### ISSUE THREAD

**Issue by ara4n** [matrix-org/matrix-appservice-irc#301]
The queued up M->I traffic is incredibly confusing and obnoxious

**Comment by Kegsay** [comment]
This is difficult to do.

The queued up M->I traffic is stored on Synapse. Synapse will queue up messages and then send them to the AS. The AS doesn't know that these messages happened a long time ago and should therefore drop them to the floor. We cannot reliably use `origin_server_ts` because of discrepancies over federation: this is something where a "local server ts" would be most helpful, because that will at least be consistent for all events received by the bridge.

**Comment by Kegsay** [comment]
We're doing it via `origin_server_ts` with appropriate warnings for the option. #310
