### ISSUE TITLE
Deliver a Matrix -> IRC pm once the IRC user connects

### ISSUE THREAD

**Issue by devnoname120** [matrix-org/matrix-appservice-irc#348]
Not sure how feasible it is but it would be nice to be able to send a message to a IRC user that he would receive once he connects.

**Comment by Mikaela** [comment]
How would it work with security? Even with `ENFORCE` enabled, there would be 30 seconds time to send messages to wrong nick.

**Comment by devnoname120** [comment]
- If the discussion was with an unregistered user: send the message once a user (registered or not) with the same nick appears.
- If the discussion was with a registered user: send the message once a registered user with this nickname connects.

**Comment by Kegsay** [comment]
Implementing store-and-forward semantics for IRC users feels very feature creepy for an IRC bridge. We should really be telling Matrix users that this person is not online and will not get any messages, rather than letting them be sent and have errors bounce back into the IRC admin room as they do today.

Even if we did implement this, we'd need to be careful how it was done from a UX perspective. If you message a Matrix user and they are offline, they get a push notification. We can't do that for IRC users, but the expectation will be that they get notified somehow.

**Comment by devnoname120** [comment]
From a Matrix-user perspective, I don't care if someone connects using IRC, Slack or anything, the bridge should abstract this out. Also, since the bridge tells that a user if offline if he hasn't posted a message for some time, it's not always easy to know if you can send him a message (well except sending him one and surveying the IRC Bridge Status to see if there is an error).

Do they? I know many people who use a web client from time to time and don't have any client installed on their smartphone. I don't really understand why a standard Matrix server can wait for the connection of a client to deliver him messages, but an IRC Bridge couldn't wait for the connection of an IRC client.

**Comment by MilkManzJourDaddy** [comment]
Pasted from:

> Add NoteServ' Functionality. But, Clarify if Nicknames are Registered. #372 
> 
> It is seen on Matrix where a native Matrix MXID will send to an IRC Nick', only to get a notification that the IRC user is unreachable.
> 
> The "NoteServ(er)" is common enough on IRC, albiet "Store & Forward".
> Matrix routinely stores room messages.
> IIRC, some IRC servers might have the ability to feed the last few lines, from before a Nickname connected, like XMPP.
> 
> But, when doing so, it might be important to distinguish between Registered and UNregistered Nickmames, perhaps prompting a native Matrix MXID to verity if they want to send a "NoteServ(er)"/stored message for an IRC Nickname that is not registered.
> 
> This should be considered for bridging to existing IRC networks, and Matrix IRCd alike.

Does anyone know if there is an IRCd that handles NoteServ' for **UN**registered nick's?  

I say one approach is to accept the messages if the IRC nickname is registered.  If not, pop-up a warning, and let the Matrix native MXID user decide.  

Or you could do something like an IRC "+k" channel, where the IRC nick' needs to enter a prearranged key.

Another approach, perhaps compatible with the current Matrix "Kitchen Sink" framework, already in place is, automatically send to a NoteServ' mechanism for **Registered** IRC nicknames.  And in the case of **UN**registered nick's, treat it like a standard Matrix DC room message, where there was a network error, and give the Matrix native MXID the opportunity to Redact-or-Resend, when confirming they have the correct humanoid on the other end.  

Don't **registered** IRC nick's have a flag on IRCd?

**Comment by Mikaela** [comment]
> Does anyone know if there is an IRCd that handles NoteServ' for UNregistered nick's?

Assuming NoteServ is equivalent to MemoServ, it's usually part of IRC Services package rather than IRCd (even if it acts as an IRCd which hosts the services and links to rest of the network.

There are however bots that do that such as Limnoria with the [Later plugin](https://github.com/ProgVal/Limnoria/tree/master/plugins/Later).

> Used to do things later; currently, it only allows the sending of nick-based notes. Do note (haha!) that these notes are *not* private and don't even pretend to be; if you want such features, consider using the Note plugin.

> `(later tell <nick1[,nick2[,...]]> <text>) -- Tells each <nickX> <text> the next time <nickX> is seen. <nickX> can contain wildcard characters, and the first matching nick will be given the note..`

* * * * *

> I say one approach is to accept the messages if the IRC nickname is registered. If not, pop-up a warning, and let the Matrix native MXID user decide.

I think the bridge would be unable to do it, at most it would be able to pop up an error in the admin room.

> Or you could do something like an IRC "+k" channel, where the IRC nick' needs to enter a prearranged key.

I believe most of IRC users would be unhappy with something like this.

> automatically send to a NoteServ' mechanism for Registered IRC nicknames

This would require both parties to be registered and MemoServ & similar aren't standardized or give any easy way to do this. Also what would you do if the target MemoServ inbox was full?

> And in the case of UNregistered nick's, treat it like a standard Matrix DC room message, where there was a network error,

I think this would also go over capabilities of the bridge.

> With that last bit, or generally, something like ISON "notify" would be very nice, and helpful.

> Don't registered IRC nick's have a flag on IRCd?

ISON has been deprecated by MONITOR on networks that have it enabled. You might also be interested in whoX and [account tracking with IRCv3](http://ircv3.net/irc/#account-tracking), however I don't know if the bridge does anything with IRCv3.

**Comment by Kegsay** [comment]
We're not doing this for the foreseeable.

**Comment by z3ntu** [comment]
Could we at least have some indication that the message wasn't delivered? Currently I mostly connect to a channel via an IRC client to check if a person is online and only then send a message in the PM which is quite annoying.

**Comment by Mikaela** [comment]
> How would it work with security? Even with ENFORCE enabled, there would be 30 seconds time to send messages to wrong nick.

Hi me year ago, this was done by the recent freenode spam attack also impersonating me while my IRC was down for a few weeks.

> Could we at least have some indication that the message wasn't delivered?

@z3ntu I would recommed you to open a separate issue. I imagine that the Matrix ghosts could at least messagn m.notice `nick offline` as they do when they are invited to a not-bridged channel.

Of course it would also be possible for IRC users to `/notice matrixuser user offline` and other "fun", but that doesn't seem very risky/bad for me.

**Comment by z3ntu** [comment]
@Mikaela #692
