### ISSUE TITLE
#freenode_#swift-lang:matrix.org (+r, "block unidentified") not syncing, shows as 'person'?

### ISSUE THREAD

**Issue by dtzWill** [matrix-org/matrix-appservice-irc#351]
Riot link:

https://riot.im/app/#/room/#freenode_#swift-lang:matrix.org

After registering my nick with services (and hooray for `!storepass`!), I was able to sorta-join the room (tried by accessing the URL above as well as `!join #swift-lang` results in:

* The room appears under "People", which seems odd
* The topic appears correctly, but otherwise the channel doesn't seem to be.. working?

I just ping'd my matrix handle from IRC and the message did go through, but still the rest of the channel doesn't seem to have sync'd.

Let me know if there's any more information I can provide to be helpful, thanks!
(And thanks for this great service!)

**Comment by Kegsay** [comment]
> The room appears under "People", which seems odd

You'll need to bring this up as a Riot-Web issue, it has nothing to do with the IRC bridge.

> The topic appears correctly, but otherwise the channel doesn't seem to be.. working?

The Freenode IRC bridge is not configured to automatically sync IRC membership lists to Matrix, which is why the room appears empty. Users will lazily join as they say something, which appears to be infrequently on #swift-lang. We're aware of this issue: #344

**Comment by dtzWill** [comment]
My mistake, thanks for the response!

**Comment by Kegsay** [comment]
Thanks for reporting it! :smile:
