### ISSUE TITLE
Don't apply userModes to the bridge bot

### ISSUE THREAD

**Issue by Kegsay** [matrix-org/matrix-appservice-irc#354]
It makes it more difficult to respond to provisioning requests.

**Comment by madduck** [comment]
In fact, it makes it impossible:

    <MatrixBridge> @madduck:madduck.net has requested to bridge '#madduck' (https://matrix.to/#/#madduck:madduck.net) with #madduck on this IRC network. Respond with 'yes' or 'y' to allow, or simply ignore this message to disallow. You have 300 seconds from when this message was sent.
    <madduck> y
    [helix.oftc.net] MatrixBridge is in +g mode (server side ignore)
    [helix.oftc.net] MatrixBridge has been informed that you messaged them.

(and nothing happens, the authorization times out after 300 seconds)

**Comment by realitygaps** [comment]
Same here with oftc bridge.

**Comment by jywarren** [comment]
Same here! Is there anywhere I can help out on this?

**Comment by jywarren** [comment]
I'm guessing there could be a conditional added for this line? 

https://github.com/matrix-org/matrix-appservice-irc/commit/b08ba968bbf2d44589cd2e8c10006ca9d7d4cf55#diff-a9da0ba5ba40c2ef0033a8875ae6b438R158

But don't really know what i'm talking about!

**Comment by jywarren** [comment]
Perhaps `nameInfo.username === "MatrixBridge"` or something, based on this line?

https://github.com/matrix-org/matrix-appservice-irc/blob/b08ba968bbf2d44589cd2e8c10006ca9d7d4cf55/lib/irc/BridgedClient.js#L120

**Comment by jywarren** [comment]
Or, and apologies as I don't know the scope or architecture too well here, if this entire page is relevant only to bridge bots, `usermodes` could be filtered directly, or the config.yaml changed... 

OK, i'll stop speculating, but would deeply appreciate a fix! Thanks for such a great system.

**Comment by madduck** [comment]
Sounds to me like all we have to do is remove 'G' from the list of usermodes in the config file, no? In fact, this is more a bug against the bridge operator than the code, I thought.

**Comment by Mikaela** [comment]
Not directly relevant, but it might interest you that I opened an issue about this at https://github.com/oftc/oftc-hybrid/issues/47 as requested on `#_oftc_#oftc:matrix.org`.

This issue doesn't apply at freenode so hardly thanks to ircd-seven `ACCEPT`ing users when they are messaged while the oftc-hybrid issue requests the same behaviour to OFTC.

* * * * *

> Sounds to me like all we have to do is remove 'G' from the list of usermodes in the config file, no? In fact, this is more a bug against the bridge operator than the code, I thought.

This would leave the OFTC bridge vulnerable for spam which has previously took matrix.org homeserver down entirely due to the amount of messages, so it cannot be done.

* https://github.com/matrix-org/matrix-appservice-irc/issues/302
* https://twitter.com/matrixdotorg/status/808691652684640256

**Comment by jywarren** [comment]
Oh interesting. Would that behavior, if adopted on oftc-hybrid, trickle
back to the bridge bot behavior? I'm not sure how these are all
interdependent. But so MatrixBridge bot would, on messaging the chanop for
validating the bridge, automatically accept responses from the chanop,
right?

Either way, does anyone know the test suite well enough to know where a
test for usermode application might go?

On Feb 25, 2017 1:27 PM, "Mikaela Suomalainen" <notifications@github.com>
wrote:

Not directly relevant, but it might interest you that I opened an issue
about this at oftc/oftc-hybrid#47
<https://github.com/oftc/oftc-hybrid/issues/47> as requested on
#_oftc_#oftc:matrix.org.

This issue doesn't apply at freenode so hardly thanks to ircd-seven ACCEPTing
users when they are messaged while the oftc-hybrid issue requests the same
behaviour to OFTC.
------------------------------

Sounds to me like all we have to do is remove 'G' from the list of
usermodes in the config file, no? In fact, this is more a bug against the
bridge operator than the code, I thought.

This would leave the OFTC bridge vulnerable for spam which has previously
took matrix.org homeserver down entirely due to the amount of messages, so
it cannot be done.

   - #302 <https://github.com/matrix-org/matrix-appservice-irc/issues/302>
   - https://twitter.com/matrixdotorg/status/808691652684640256

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/matrix-org/matrix-appservice-irc/issues/354#issuecomment-282502644>,
or mute the thread

**Comment by Mikaela** [comment]
I am not fully sure if I understand your question correctly, but if Hybrid IRCd fixed the previously linked issue and OFTC upgraded their instances of Hybrid IRCd, when the bot sent a message to channel op, the channel op would be able to reply directly regardless of umodes of the bot. I hope this answered your question.

However OFTC will probably be taking a long time for upgrading their IRCds, so it shouldn't be waited on. I posted it here as curiosity and I was adviced to open it when I asked if there is any intent behind the current behaviour as opposed to the suggested behaviour.

*I am feeling a little ill and apologise if my typing makes no sense.*

**Comment by jywarren** [comment]
Oh, ok, that makes sense; I'm going to clone `matrix-appservice-irc` and see if I can get tests to pass. 

But from your notes on spam, do I understand that we can't follow the current name of the issue to solve the problem (`Don't apply userModes to the bridge bot`) as it will expose the bridge bots to spam?

What about an alternative in which the MatrixBridge bot manually ACCEPTs the chanop which it is asking for verification?

**Comment by jywarren** [comment]
And hope you feel better, thanks!

**Comment by tuxayo** [comment]
IIUC it's not related to the issue when an OFTC user sends a PM to a bridged Matrix user, they get:
```
is in +g mode (server side ignore)
has been informed that you messaged or invited them.
```

It's about manually bridging rooms right? (https://github.com/matrix-org/matrix-appservice-irc/issues/354#issuecomment-277116987)
