### ISSUE TITLE
How to troubleshoot the IRC Bridge

### ISSUE THREAD

**Issue by TheNeikos** [matrix-org/matrix-appservice-irc#357]
The situation right now is that Irc -> Matrix works without problem, however Matrix -> IRC does not.

How could I troubleshoot this?

**Comment by Kegsay** [comment]
Ask on `#matrix-irc` on Freenode or `#irc:matrix.org` on Matrix.

I'm guessing that when you created your registration file you did not specify the URL of the bridge, but instead specified the URL of the homeserver, so when Matrix messages are sent, the homeserver isn't sending the messages to the bridge.

Closing this since there isn't really anything actionable here: GH issues is a pretty terrible support channel.
