### ISSUE TITLE
Update minimatch

### ISSUE THREAD

**Issue by FSMaxB** [matrix-org/matrix-appservice-irc#359]
When running `npm install` I get this deprecation warning:

```
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
```

I think this library should probable be updated.

**Comment by t3chguy** [comment]
If you install using `npm i -g matrix-appservice-irc` rather than `git clone` you will not have the outdated minimatch package installed, its a devDependency of a devDependency, so the other way to avoid it is to use `npm install --production` after a `git clone`

Only way to get rid of this warning in a dev environment is to replace `istanbul`

**Comment by t3chguy** [comment]
This is not a library we depend on directly, but istanbul depends on it and we depend on that in two places. Above are PRs to update it in both of these places to fix this.

**Comment by t3chguy** [comment]
Both of the needed PRs have been merged, I believe this can be closed.
