### ISSUE TITLE
disable pm spam filtering on gimpnet plz

### ISSUE THREAD

**Issue by ara4n** [matrix-org/matrix-appservice-irc#390]

**Comment by Mikaela** [comment]
> I don't understand that issue, unsetting +R(?) why? And how soon would someone with grievance against Matrix repeat OFTC at GIMPnet taking matrix.org down?

* https://matrix.to/#/!SudviOJlimDvrGdFCY:matrix.org/%241489483944647905JIldA:matrix.org

I was given https://matrix.to/#/!DgvjtOljKujDBrxyHk:matrix.org/%241489482536639320KRjYr:matrix.org as response and I still think this would be a bad idea. 

I also have impression that OFTC and GIMPnet might be roughly the same size, but I don't have LUSERS available at the time of typing.

**Comment by Kegsay** [comment]
Needs some justification really. We're exposing matrix.org Synapse to a spam vector by disabling it.

**Comment by ara4n** [comment]
"they're a small network, and don't have a PM spam problem, and nobody 
bothers to register nicks so it's seriously breaking the usability of 
that bridge."

**Comment by csoriano89** [comment]
Heya, I was discussing with Kegsay previously about this.

Seems this is done because of fear matrix will go down if some spammer comes (although so far we didn't have such problems with the sysadmins we have) so I understand the concern.

Actually most of the regular contributors are registered, but there are quite a lot of "lurkers" that are usually not, and gimpnet allows it. But it's true some of the regular contributors are not registered and found this issue, which is unpleasant for them when it's something important (releases, etc) and the messages simply get lost, since they just see they are talking to another user in the gimpnet but the other doesn't amswer.

Kegsay also mentioned no notification about the message being rejected is received on the client probably because our native clients are using libpurple and telepathy. So I'll check that out and see where the issue is.

I'll come back with the findings and ask those people to comment in here if there is something that is difficult to deal with on our side.

**Comment by csoriano89** [comment]
See https://github.com/matrix-org/matrix-appservice-irc/issues/382 for the issue of not getting any message back that I was mentioning n the previous comment.

**Comment by mcatanzaro** [comment]
I don't think disabling spam filtering on just GIMPNet is an acceptable solution. I use freenode too, and it's really crazy if PMs to Matrix users get dropped silently with absolutely no notification to either user that the message was dropped. I don't know how to solve this problem, and maybe there is no way to solve it, but this is going to be a serious blocker for GNOME.

We don't require users to register on our network, and cannot do so now because it requires major work in Empathy to support that nicely.

**Comment by Mikaela** [comment]
If I understood correctly, this is not an Matrix IRC bridge issue, but this is an issue with

* A) IRC clients people are using (Pidgin/Empathy are not proper IRC clients as libpurple/telepathy aren't designed with IRC in mind).
* B) IRC networks which people are using.

The expected behaviour is receiving error message such as 

> ⓘ [486] Mikaela, You must log in with services to message this user 

when messaging user with umode +R (which Matrix ghosts are using).

*This message is copied from charybdis-3.5.0-dev on KiwiIRC.*

* * * * *

In any case I believe it's unacceptable to disable +R with Matrix bridges just for one network as the OFTC case happened taking matrix.org down and if it was known that GIMPnet didn't have the protection, someone with grievance against Matrix could simply go there and reproduce the OFTC issue.

For the full discussion about this subject at Matrix, I request you to please read beginning from https://matrix.to/#/!SudviOJlimDvrGdFCY:matrix.org/%241489483944647905JIldA:matrix.org ending to where you see people changing the subject.

**Comment by Mikaela** [comment]
* C: I tested it and it appears that the umode +g (thus probably also umode +R) errors are silently eaten by the bridge and error on them is not being sent to the admin room.

I am not sure if you were trying to communicating this, but this is an issue with the bridge.

**Comment by ara4n** [comment]
@mikaela's understanding is correct; i think this is just IRC users missing the "you must register to message this user" errors.

we've now disabled -R on gimpnet entirely, as it was causing mass confusion, and the network isn't big enough to suffer from PM spam.  If this situation changes we'll put +R again.

**Comment by mcatanzaro** [comment]
I can confirm that no such message is displayed to Empathy users when a PM is dropped.

**Comment by Mikaela** [comment]
> * C: I tested it and it appears that the umode +g (thus probably also umode +R) errors are silently eaten by the bridge and error on them is not being sent to the admin room.

This now has it's own issue at https://github.com/matrix-org/matrix-appservice-irc/issues/391
