### ISSUE TITLE
Membership of a freenode channel lost

### ISSUE THREAD

**Issue by lampholder** [matrix-org/matrix-appservice-irc#432]
Was able to rejoin, but all history was lost.

Further details in the rageshake logs.

**Comment by Mikaela** [comment]
Could you open the issue more, what exactly happened and where? 

I don't think rageshake has anything to do with the IRC bridge and I am not sure if Kegan has access to those. 

Have you seen https://mikaela.info/r/matrixircfaq ?

**Comment by Kegsay** [comment]
This isn't an IRC bridge problem. The bridge will kick for any number of reasons (idle, unregistered (critically need to be registered via `!storepass`), kicks/ban on the channel, etc). The problem is that when they rejoined they lost history up to the point that they were kicked. They should have had that history.

Making a Synapse issue for it.

**Comment by Kegsay** [comment]
https://github.com/matrix-org/synapse/issues/2212
