### ISSUE TITLE
Clear IRC nickTemplates

### ISSUE THREAD

**Issue by betz** [matrix-org/matrix-appservice-irc#437]
Hi,

I updated the nickTemplate of ircClients, but when restarting, it stays the same.
I guess it is stored somewhere, can this be cleared?

Cheers!
Tom

**Comment by Kegsay** [comment]
Yes it is stored in `users.db`. Look for lines which contain `client_config` and you'll see something like:
```
{
	"client_config": {
		"localhost": {
			"nick": "example[m]",
			"username": "examplel_6"
		}
	}
}
```

The `nick` is the nick that will be used on connect. The `username` is the IRC username that will be used on connect. If you are running a public bridge which has an i-line, it is NOT safe to remove these lines and start over because the calculated `username` may be different, which can allow users to escape bans.

If you are running a personal bridge, you can delete or modify as you like since the IRCd will be basing connections from your IP address and not the `username` field.

**Comment by betz** [comment]
Thanks
