### ISSUE TITLE
!storepass fails on OFTC

### ISSUE THREAD

**Issue by EionRobb** [matrix-org/matrix-appservice-irc#459]
The `!storepass` command does not work with the admin user for OFTC, eg `@oftc-irc:matrix.org` as the NickServ on OFTC uses a different parameter order for the "PASS" command than other servers

When asking NickServ "help identify" on OFTC and Freenode the results are:
OFTC:
> `Usage: IDENTIFY password [nick]`

Freenode:
> `Syntax: IDENTIFY <nick> <password>`

**Comment by Mikaela** [comment]
The `!storepass` command only stores string to be sent on connect with the `PASS` command which I think was originally meant to be used with password protected IRC servers.

Nowadays some IRC servers use it for automatically identifying users to services, in case of freenode [as the wiki says](https://github.com/matrix-org/matrix-appservice-irc/wiki/End-user-FAQ#and-do-it-automatically) you can use `username:password` for sending both or only `password` to send the password.

Whether this forwarding is setup or not is matter of IRCd config and has nothing to do with the syntax which IRC services use, so I think this issue is invalid.

If I recall correctly, `#_oftc_#oftc:matrix.org` has said that they don't support `PASS` and only certfp which the IRC bridge again doesn't support.

**Comment by EionRobb** [comment]
No, I'm getting a response from NickServ saying along the lines of "incorrect password for user {my password}"

**Comment by EionRobb** [comment]
Hmm ok, maybe you're right, I've just gone through the chat logs to see what the exact error message was. I might have done something dumb here. Once the OFTC bridge is working again I'll try and reopen if it is a problem.

**Comment by makeworld-the-better-one** [comment]
@EionRobb Did you ever get this command to work with OFTC? Trying to figure it out now.

**Comment by Mikaela** [comment]
@makeworld-the-better-one you may `!storepass` so that the matrix-appservice-irc automatically sends whatever you give it with `PASS` command, but the OFTC IRC server doesn't support that (unless they have started supporting it recently). Your best bet would be https://github.com/matrix-org/matrix-appservice-irc/issues/747 which OFTC officially supports.

**Comment by eternaleye** [comment]
Something I'd like to bring up - #1128 chose a workflow where the Matrix user hands the bridge a private key, but it'd likely be more sensible to have a command to _generate_ a key (and certificate), which the user then registers with the network. This avoids passing private key material around, which is generally frowned upon.
