### ISSUE TITLE
The bridge doesn't respect REMOVE (aka forced PART)

### ISSUE THREAD

**Issue by Mikaela** [matrix-org/matrix-appservice-irc#460]
`REMOVE` is a command to force user to `PART` the channel, I think it's designed for cases where the user is automatically rejoining on kick.

When I remove a Matrix user, I would expect them to be removed on the Matrix side too, but instead they silently stay in the room to rejoin when they say something next time.

```
<-- mijris[m] (mijrischat@gateway/shell/matrix.org/x-ykfippqwepiopoqo) has left ##Mikaela (requested by Mikaela (test#?))
<@Michaela> !ping
--> mijris[m] (@mijris:chat.weho.st) (mijrischat@gateway/shell/matrix.org/x-ykfippqwepiopoqo) has joined ##Mikaela
mijris[m] (Notice) pong! 2017-06-21 05:33:18
```

* * * * *

Addition: Wednesday, 21 June 2017 10:54 (UTC+0300)

It appears that REMOVE isn't documented almost anywhere, but it does exist at freenode. The only documentation that I can find is [Charybdis extensions README](https://github.com/charybdis-ircd/charybdis/blob/release/3.5/extensions/README#L44-L47) (thanks @Spydar007 for linking me to it) which only says:

```

m_remove.c     - REMOVE - Implements /REMOVE, which allows a channel op to
                          force-part a problematic user from a channel.  Most
                          likely, you don't want this, because it is non-standard,
                          and easily worked around for autojoin purposes.
```

**Comment by Spydar007** [comment]
FTR, the syntax for REMOVE is `/quote REMOVE #channel nick :reason`. You only need include the colon at the start on the reason if your reason is more than a single word.

**Comment by spb** [comment]
Note that this appears to the removed client as a simple PART message originating from the target, the same as when a client-initiated PART is reflected to the client that issued it.

Note also that this issue is more fundamental than not understanding REMOVE. There are a number of other scenarios, across most IRCd software, in which a user will PART, or JOIN, a channel without being initiated by that client; it's important that any client software understands that as part of basic IRC state tracking. Clients that fail to handle that situation gracefully have resulted in a great deal of annoyance and channel spam over the years, and usually end up getting banned as a result.

**Comment by Half-Shot** [comment]
I am going to remove the p1 tag and I don't believe supporting a barely documented extension is worth doing for the bridge. We are working on a PR which honors PARTs aimed at Matrix-side users and kicks them appropriately.

**Comment by Half-Shot** [comment]
I am assuming if we now do #754 (we act on PARTs from the ircd), then this is fixed?

**Comment by Mikaela** [comment]
I think so, especially if the acting is removing the Matrix user from the room the server has parted them from.
