### ISSUE TITLE
Can't change nick anymore on Freenode (err_banonchan)

### ISSUE THREAD

**Issue by akien-mga** [matrix-org/matrix-appservice-irc#475]
As usual when the IRC bridge is restarted, I lose my nickname as it's guarded and I never look at Matrix right at the moment when I should identify within 30 seconds...

Nevertheless, usually I can reclaim my nick with NickServ and identify again, but since yesterday I can't set *any* nick with @appservice-irc:matrix.org; it answers all !nick queries with: Failed to change nick: err_banonchan

```
!nick Akien
Failed to change nick: err_banonchan
!nick Akien___
Failed to change nick: err_banonchan
!nick NonbannedNick
Failed to change nick: err_banonchan
```

Did appservice get itself banned?

**Comment by Mikaela** [comment]
Usually that means that unidentified users are banned/quieted in some channel.

I would recommend `!storepass nick: password` for freenode and in case the ban is for unidentified users, you could open a direct chat with `@freenode_NickServ:matrix.org` and say `identify nick password` and try `!nick` again. Alternatively with NickServ `regain nick` after identify might work.

In case you don't want to store your password, I would also recommend you to take a look at `/msg nickserv help access` to not get guested.

I would also request you to use `#irc:matrix.org` for support instead of this issue tracker.

**Comment by akien-mga** [comment]
Thanks for the `!storepass` trick and the instructions to login with NickServ *before* trying to change the visible nick, that did the trick.

> I would also request you to use #irc:matrix.org for support instead of this issue tracker.

Duely noted - I just thought it might be a more global bridge issue, but glad it can easily be solved on the user end :)
