### ISSUE TITLE
Users of bridged channel missing in IRC

### ISSUE THREAD

**Issue by Flexmaen** [matrix-org/matrix-appservice-irc#534]
I wonder what's wrong there.

I bridged the #ctg:matrix.org to #ctg on Freenode, with the result that some users are missing on IRC.

Here you see the users of the Matrix room:
![ctg_problem_matrix](https://user-images.githubusercontent.com/6330276/34342489-e3904c7e-e9b1-11e7-9fc5-d6232cd784ae.png)

Here you see the users in the IRC channel:
![ctg_problem_irc](https://user-images.githubusercontent.com/6330276/34342488-e3716d86-e9b1-11e7-80da-7d49f0d74658.png)
(this means sky76, curdla and diechtelayer missing).

I used the integrations function to establish the bridge. Also we tried leaving and joining with the users, or unlinking and re-establishing the bridge again:
![ctg_problem_integrations](https://user-images.githubusercontent.com/6330276/34342487-e34d767e-e9b1-11e7-8169-414f547b642c.png)

Would be great if someone could help figuring out what the problem is.

**Comment by Mikaela** [comment]
2017-12-22 and 2017-12-25

![](https://teleirc.mikaela.info//file_1712.jpg)

![](https://teleirc.mikaela.info//file_1714.jpg)

**Comment by mcatanzaro** [comment]
GNOME is experiencing this same problem. The Matrix user who has joined a bridged room in Matrix thinks she is present in the IRC room, because she can see all the discussions bridged to Matrix. But in IRC, the user is not present and so IRC users think the Matrix user is offline.

We have discovered that when this situation occurs, the Matrix user can rejoin the IRC room by typing any message into the IRC room. This causes the bridge to rejoin the user to IRC in order to send the message. But the Matrix user has no way to know he was dropped from the IRC room without using an IRC client to check.

**Comment by ara4n** [comment]
Which room is this?

**Comment by mcatanzaro** [comment]
> Which room is this?

I think this can happen in any bridged GIMPNet room. I've previously noticed it in #epiphany. Today, it occurred for Abderrahim[m] in #release-team. The message he sent 23 minutes ago today (18:05 UTC) caused him to rejoin #release-team, where he thought he was already present.

I have seen this occur for users of the matrix.org and igalia.com instances. I have not yet seen it for any gnome.modular.im users, but I expect that's just because we don't have many users on that instance and haven't noticed it yet.

**Comment by ara4n** [comment]
Turns out the GIMPnet bridge had hit the connection limit (3000 users). Have increased to 6000 and restarted.

This is (probably) unrelated to the original Freenode bug here.

**Comment by Mikaela** [comment]
I am seeing some freenode channels suffering the opposite issue, IRC users not appearing at Matrix from freenode.

**Comment by Flexmaen** [comment]
> GNOME is experiencing this same problem. The Matrix user who has joined a bridged room in Matrix thinks she is present in the IRC room, because she can see all the discussions bridged to Matrix. But in IRC, the user is not present and so IRC users think the Matrix user is offline.
> 
> We have discovered that when this situation occurs, the Matrix user can rejoin the IRC room by typing any message into the IRC room. This causes the bridge to rejoin the user to IRC in order to send the message. But the Matrix user has no way to know he was dropped from the IRC room without using an IRC client to check.

This is not the issue I reported.
This issue was opened because a user did not show up in IRC permanently.

In the meantime, the way the bridge works was changed. Matrix users will only show up in IRC if they are active. So in fact, **the problem I reported is now solved**, since the user now got other chances to join IRC.

I think the behaviour you mention is part of the change. Matrix users are not shown in IRC if they are not active (e.g. did not run their client). If they join, they will be able to read all the previous conversaionts and will also be seen in IRC. I do like this change, because all these inactive one-time Matrix users will now be removed from IRC until they login to their client again. Also this fixed the problem I reported. The only disadvantage might be that you cannot ping inactive Matrix users from IRC. However this might not be useful anyway, if they are not using their client.

So I'd close this issue now, since it is solved.
If you think that there is another issue with users not showing up in IRC altough they should, then I guess it's better to open a new issue.
