### ISSUE TITLE
How to delete this channel?

### ISSUE THREAD

**Issue by wsdjeg** [matrix-org/matrix-appservice-irc#576]
as a admin of IRC channel, #vim-china, how could I disable 

`https://riot.im/app/#/room/%23freenode_%23vim-china:matrix.org`?

**Comment by brycied00d** [comment]
Hi @wsdjeg, you're referencing a "dynamically bridged" room, meaning that it's bridged solely because any Matrix user can connect to any Freenode channel; no individual specifically bridged that channel.

I recommend you check out https://github.com/matrix-org/matrix-appservice-irc/wiki/Channels-from-which-the-IRC-bridge-is-banned for some ideas on how to prevent these Matrix users from joining the channel.

**Comment by wsdjeg** [comment]
Thanks, I have done. and now this channel is disabled, and I am using `#vim-china:matrix.org` instead
