### ISSUE TITLE
Unpin node-irc

### ISSUE THREAD

**Issue by Half-Shot** [matrix-org/matrix-appservice-irc#584]
For some reason we are pinned against ``matrix-org/node-irc#b1614bc784200c65247784d7b9e9ab867140412d`` which is not ideal if we want to make changes.

~Also, we import the regular node-irc library which is pinned at 0.0.4. No idea why.~ ( We don't, I was fidding with my project locally, oops)

**Comment by Kegsay** [comment]
A [bugfix was done](https://github.com/matrix-org/matrix-appservice-irc/commit/640f15c58fdd16dab880c62134b395d3fe024301) in that commit which the IRC bridge required, so it was pinned to that commit.

You'll note that prior to this it was pinned to an earlier commit: pinning guarantees consistent builds, given node-irc isn't versioned hence tracking `master` is risky. YMMV though, but that's why it is the way it is.

**Comment by Half-Shot** [comment]
Yes, I should have updated this question when as I went along. This seems to make sense although we have bumped the pin to include a new error code.

**Comment by Half-Shot** [comment]
We're continuing to pin for the time being, though at some point it would be good to start versioning or use a maintained fork.

**Comment by Kegsay** [comment]
Unless something has changed in the past 2-3 years it's unlikely there exists a more maintained fork than our one. The `martynsmith` people got in touch with me a while back asking to make our one the canonical maintained one, to which I politely declined because `node-irc` is simply here to support the IRC bridge, and we don't want to have to be spending additional time maintaining other (potentially clashing) use cases people have for it.
