### ISSUE TITLE
Tests open new instances of several modules per env, using massive amounts of memory.

### ISSUE THREAD

**Issue by Half-Shot** [matrix-org/matrix-appservice-irc#614]
In particular, we load olm and all it's nativeness into memory *every* *single* *test*.

The effect of this issue is we leak 33MBs of memory per test..and we have 144 tests. If you do the math, that's a lot of memory being eaten.

**Comment by Half-Shot** [comment]
If you have a minute, could you add anything to this @Kegsay? I wonder if you encountered this in your travels

**Comment by Kegsay** [comment]
I haven't encountered this problem before. Even if what you say is true, the last time I checked the tests are run sequentially, not in parallel so the previous test's memory will be rapidly GC'd away.

I'm skeptical that Olm is loaded N times (1 for each test) rather than once only, given imports get cached by node, do you have any evidence that this is indeed the case? It's possible the behaviour of node/npm/jasmine has changed which could result in leaks, but I'm not aware of anything in particular.

**Comment by Half-Shot** [comment]
I had it wired up to memwatch a while back, but a quick and dirty demonstration of memory usage is:
![test_mem](https://user-images.githubusercontent.com/2072976/42755029-b1865520-88ee-11e8-94a9-579edde947c8.png)

For olm being a culprit, I attached and inspected it and found the vast majority of heap usage was modules being loaded in and objects being kept:

![image](https://user-images.githubusercontent.com/2072976/42755814-905909bc-88f1-11e8-9ca9-b5b522c92535.png)

The memory usage graph in general looks like it isn't GCing :(

**Comment by Half-Shot** [comment]
I fixed this a long time ago, and if memory serves we found that the IrcBridge instances were hanging around forever. Not only did we solve the memory issue, but the tests run faster.
