### ISSUE TITLE
IRC bridge to mode +r channel prevents users from joining

### ISSUE THREAD

**Issue by mstenta** [matrix-org/matrix-appservice-irc#653]
There has been a flood of IRC spam over the past month (eg: https://freenode.net/news/spam-shake), and one of the only recommended ways of combating this seems to be setting mode +r on the channel, which restricts it to only users that have registered their username with Freenode.

If you have a Matrix.org room bridged to the IRC channel (with mode +r), Matrix.org users are prevented from joining the Matrix.org room. They get immediately kicked by @appservice-irc:matrix.org.

For example:

```
[example-username] joined the room.
@appservice-irc:matrix.org kicked [example-username]. Reason: IRC error on #[example-channel]: err_needreggednick
```

This essentially makes the Matrix.org room impossible for others to join, even when it is a public room.

I'm not sure if there is any way to solve this, though - it seems like a tricky problem. Because @appservice-irc:matrix.org needs to create new users in the IRC room, but it is not going through the whole process of registering them.

So it seems that the IRC bridge can only be used on channels that do not have mode +r. Which means lots of persistent spam.

On the bright side, it seems that the spam is only showing in the IRC room, and is not being synced over to the Matrix.org room in most cases.  It was earlier this month, but doesn't seem to anymore. Still, I thought it would be good to document this limitation, in case anyone else is experiencing it and has some advice to share.

Thank you for this wonderful service! :+1: :-)

**Comment by Half-Shot** [comment]
>I'm not sure if there is any way to solve this, though

You register yourself on NickServ and join the room?

**Comment by makeworld-the-better-one** [comment]
I am having this issue as well. It prevents me from joining and talking in IRC channels. Will this be resolved soon?

**Comment by mstenta** [comment]
@makeworld-the-better-one - I'm not an expert on how this works, but it strikes me as something that is inherently difficult to resolve.

It seems that, currently, if the IRC bridge is unable to create a user in the IRC room, then it kicks the Matrix.org user out of the Matrix.org room as well. Perhaps this logic could be changed, so that it doesn't kick the Matrix.org user... but that would mean that Matrix.org users are no longer created in IRC - which is essentially the whole point of this bridge.

One idea might be: instead of creating new users for each Matrix.org user in the IRC room, just create one (ie: just named "@appservice-irc:matrix.org") - and have that user speak on behalf of any Matrix.org users in IRC. That one user could then be registered with Freenode (and other servers), so that it is allowed to join the room.

**Comment by makeworld-the-better-one** [comment]
That second solution sounds great. Any idea if it can happen?

**Comment by Mikaela** [comment]
If https://github.com/matrix-org/matrix-appservice-irc/wiki/End-user-FAQ#how-do-i-registeridentify-to-nickserv doesn't help you, I would suggest asking the channel ops to setup another solutioon against spam like.

* mode +S requires TLS connection for joining
* mode +be $~a *!*@gateway/shell/matrix.org/*
* mode +q $~a & /cs flags #channel +V *!*@gateway/shell/matrix.org/*
* MODE +m & setting a bot to autovoice everyone with some delay from joining to the channel. 

I don't think IRC networks would be happy if the bridge started spamming services with random registrations without user interaction. I think the only way this could be fixed by matrix-appservice-irc would be it starting to pretend being IRC server and link to the network as a server in which case it could possibly claim everyone to be registered as some illegal account which IRC services wouldn't allow registering.

**Comment by mstenta** [comment]
Thanks @Mikaela ! I will research these options.

**Comment by Mikaela** [comment]
> Perhaps this logic could be changed, so that it doesn't kick the Matrix.org user... but that would mean that Matrix.org users are no longer created in IRC - which is essentially the whole point of this bridge.

I think this would make at least freenode and if not more IRC users unhappy as it would be different from traditional IRC and Matrix users could be considered as spying.

> One idea might be: instead of creating new users for each Matrix.org user in the IRC room, just create one (ie: just named "@appservice-irc:matrix.org") - and have that user speak on behalf of any Matrix.org users in IRC.

I think this was how a very initial version of the bridge functioned and how e.g. Gitter bridge works, but I fear it would have restrictions too such as how to ban abusive Matrix user without using Matrix and it would be easier to just ban everyone using Matrix and problem solved.

> Thanks @Mikaela ! I will research these options.

You're welcome, I am thinking of typing something about them to the FAQ.

**Comment by makeworld-the-better-one** [comment]
@Mikaela Thank you. I'm in the process of registering my nick, although at the moment @appservice-irc:matrix.org seems to be down, so I haven't finished. On the other hand I'm not being kicked anymore. Thanks for the help, I might report back later!

**Comment by Mikaela** [comment]
You're welcome and sorry for mass commenting, but...

* https://github.com/matrix-org/matrix-appservice-irc/wiki/End-user-FAQ#i-am-a-chanop-and-have-a-spam-problem-how-can-i-fix-it-without-affecting-matrix-users - something to maybe link the channel ops instead of this issue?
* https://github.com/freenode/ircd-seven/issues/137 _No way to indefinitely exempt clients from +r_ which is the freenode-side issue which I think would also help resolve this case.

**Comment by mstenta** [comment]
@Mikaela - I am using the first two suggestions you wrote about in the [End user FAQ](https://github.com/matrix-org/matrix-appservice-irc/wiki/End-user-FAQ#i-am-a-chanop-and-have-a-spam-problem-how-can-i-fix-it-without-affecting-matrix-users): `MODE +S` and `MODE +be $~a *!*@gateway/shell/matrix.org/*`

It seems like that will work well for our needs. Thanks again!

**Comment by Mikaela** [comment]
I think this could be closed?

**Comment by tgr** [comment]
> You register yourself on NickServ and join the room?

That does not seem to work either (now, anyway), per #938.
