### ISSUE TITLE
We should allow users to store their own usernames

### ISSUE THREAD

**Issue by Half-Shot** [matrix-org/matrix-appservice-irc#673]
Because alas we can't really enable SASL if we also generate the usernames.

**Comment by Mikaela** [comment]
I think alongside this there should be a command for storing SASL password separately unless it's merged to the command to set SASL username, as !storepass stores the PASS command which may be required for logging into the services or using a separate connect block on the IRCd or plain backwards compatibility as `username:password` is used by many users for automatically identifying to freenode and it won't work as SASL password.

**Comment by Mikaela** [comment]
Additional consideration coming to my mind: this shouldn't change the ghost's ident at IRC or the opers will be unhappy as bans are usually set on `user@host` instead of specific realnames. Failing to provide unchangeable usernames will likely result losing connection limit exception to the network.

**Comment by Half-Shot** [comment]
This is now a thing as of the libera bridge. It's not perfect, as it's too harsh on requirements but as a feature it exists.
