### ISSUE TITLE
Freenode channels not listed in Room Directory of Matrix clients

### ISSUE THREAD

**Issue by v3ree** [matrix-org/matrix-appservice-irc#708]
I tried selecting the Freenode protocol in the Room Directory in Fractal and Riot clients in order to see the IRC channels list. But only a few of them show up. I can /join a specific freenode channel, but it just does not appear in the room list.

Reproduction:
 - Go to Room Directory in Matrix Client
 - Select Freenode protocol
- Search for (all or some specific) channel
- Result: room/channel cannot be found or are not displayed.
 
Version: currently implemented
IRC network: irc.freenode.net

![fractal freenode room directory list problem](https://user-images.githubusercontent.com/25938184/48086980-cc4bc900-e206-11e8-8eb8-1b8ca9ff80fe.png)

**Comment by t3chguy** [comment]
The room directory only shows existing rooms, when you join a room it may get lazily created but before that join attempt it may or may not exist

**Comment by Half-Shot** [comment]
Closing because we do not plan to implement channel searching.

**Comment by johan-boule** [comment]
This is highly confusing. Some clients do not seem to make it possible to join a channel if it's not listed. So, if I understand it, only the channels that are already bridged will be listed, and if it's not listed, you can't join it to trigger the bridge creation? I don't even remember how I managed to do that a year ago or so. It used to work with the old riot.im app since I was able to create a few bridges.
Also, doesn't IRC have channel modes that make them invisible to list commands?
