### ISSUE TITLE
Why can't !storepass automatically identify you

### ISSUE THREAD

**Issue by aaronraimist** [matrix-org/matrix-appservice-irc#724]
All the time I see people who ran !storepass but are confused why they can't join channels (one example https://matrix.to/#/!QtykxKocfZaZOUrTwp:matrix.org/$15497295442122746TOVKV:matrix.org?via=matrix.org&via=half-shot.uk&via=disroot.org). Honestly I was confused the first time I set it up to but that was in 2016 or something so I haven't had to worry about it much.

From the outside knowing nothing about the irc bridge, it seems like it would be simple for it to just send the same IDENTIFY whatever that it does when the bridge is restarted.

**Comment by Mikaela** [comment]
I think part of the problem is that there is no standardized way of identifying to IRC or it's not supported by ~anyone.

When you do !storepass, you store the password as a server password which is sent only during connect as `PASS password` to the IRC server and I think it may not do anything if it's sending after you are successfully connected. Different IRC services have different ways of identifying, with Atheme (freenode) supporting `/msg nickserv identify username password`, Anope (Rizon) being `/msg nickserv identify password`, I think there is also `/msg nickserv identify password username` somewhere, and I am forgetting Quakenet `/msg Q@quakeserver.quakenet.net auth` or something similar.

The standard would be SASL 3.2 which IIRC allows identifying at any time, but that also depends on cap-notify and it's not supported on freenode and would depend on #673 or whichever issue is tracking SASL.

**Comment by aaronraimist** [comment]
Hmm that makes sense but couldn't you just disconnect and reconnect a user when they do !storepass?

**Comment by Mikaela** [comment]
I think I cannot answer that, but I wonder if it would be unexpected for people as they may be on 120 channels at maximum on freenode and there may be brief time for losing messages and similar.

I think that maybe a better solution would be having a !reconnect command and telling people to run it if they want !storepass to apply immediately.

However there are still networks that don't support PASS such as OFTC which requires certfp.

**Comment by rohieb** [comment]
For reference, some networks (at least [Freenode](https://freenode.net/kb/answer/registration#logging-in)) allow setting username as part of the server password, so you can use `!storepass yourusername:password` with the IRC bridge.

**Comment by Half-Shot** [comment]
In any case, #864 fixes the specific issue.
