### ISSUE TITLE
Implement better UX to set up plumbed rooms

### ISSUE THREAD

**Issue by vranki** [matrix-org/matrix-appservice-irc#786]
I'm trying to bridge and existing matrix room to a irc channel.

This seems to be really tedious. Instructions for doing so are not found in the
bridge docs (although AFAIK this is a feature of the bridge) so I'm following
instructions at https://syscom.utwente.io/info/matrix/irc/ircnet/ ("Can I bridge an existing Matrix room?")

Currently the http requests return 502 Bad Gateway for unknown reason and there's no way for user to debug the issue.

I'd suggest adding a command for the bridge bot to plumb an existing room to irc.
Syntax could be something like:

!plumb #channel !qCGPUgcYVroomidXYZ  op_nickname @user:example.org

This should return sensible error messages as needed.

**Comment by silkeh** [comment]
Chiming because I wrote the linked documentation. Let me know if that information has to be improved.

A command would *vastly* improve the experience for users.

Beyond just the UX there are also some problems with the way bridging currently works:
The request requires a room ID, not an alias. Synapse cannot join a room ID it doesn't know about.
In order to work around this you have to invite the user to the room, but that doesn't work if you're not in the provisioning process. This results in having to do some steps in parallel with the actual HTTP request to get the right result (hence *"continue with the next steps while this request is being performed"*).
