### ISSUE TITLE
NickServ and ChanServ don't reply to commands after inviting them to a room

### ISSUE THREAD

**Issue by dannycolin** [matrix-org/matrix-appservice-irc#926]
**Step to Reproduce**

1. Open a private chat with @_oftc_NickServ:matrix.org
1. Type any command (e.g help)

**Actual Behavior**

Nothing happens

**Expected Behavior**

NickServ should respond to the command. For example with `help`, it should show the list of available commands.

**Additional Notes**

~~I wondering if it could be related to #924 since it only occurs with OFTC. Other IRC servers like Freenode and Moznet work fine.~~
Now, I also have that problem with Freenode

**Comment by sbts** [comment]
This seems to be a common issue.
It goes hand in hand with multiple invites from nickserv (at least on freenode)

The problem has been present for over a month, likely quite a bit longer

**Comment by jasonblewis** [comment]
See also #944

**Comment by pavlix** [comment]
Today I have the same issue with `@freenode_ChanServ:matrix.org`. It simply doesn't answer.

**Comment by dannycolin** [comment]
> Today I have the same issue with `@freenode_ChanServ:matrix.org`. It simply doesn't answer.

I can confirm (and will update the issue title). 

Also, I found out that if I connect to an IRC client, login to my Freenode account via NickServ then it will send me a message on Matrix saying someone as logged in on my account from a different client. In this room (on Matrix) created by NickServ, commands work. IOW, it seems like the problem is unidirectional, meaning that it's only when I try to invite NickServ to a room that it fails.

**Comment by Half-Shot** [comment]
Does NickServ actually join the room when you invite it?

**Comment by Half-Shot** [comment]
Also probably more importantly, is your account hosted on matrix.org?

**Comment by dannycolin** [comment]
> Does NickServ actually join the room when you invite it?

Yes.

> Also probably more importantly, is your account hosted on matrix.org?

Yes.

**Comment by Half-Shot** [comment]
Curious, then this is a new and exciting failure mode.

**Comment by pavlix** [comment]
My current situation:

  * NickServ (OFTC) joined the room but **doesn't reply** to commands.
  * Riot shows I'm in various rooms but using another IRC client I **don't see myself** there.
  * Matrix seems to leak at least some information to me (people joining and leaving a channel) even though I **don't seem** to be actually **connected** to OFTC and/or joined to the channel(s).
  * I usually get NickServ at Freenode and ChanServ at OFTC automatically inviting me to talk to them but usually **can't talk** to the other combinations.
  * When I ask for my nickname using `!nick`, I'm `pavlix`. When I ask to change my nickname to something else, they say I'm **not connected** to the server!
  * I **don't seem** to get automatically **identified**.
  * I wonder, if I can invite myself to a channel using !join, why **can't I invite myself** using !query or something to talk to someone including NickServ and ChanServ.
  * I wonder, why there's no reliable way to **check connection status** and to **reconnect** so that I can get rid of any stale state that might affect my login.

It is not just a temporary issue, it's been failing for a few days now.

![2020-02-09-164248_563x281_scrot](https://user-images.githubusercontent.com/1082089/74106200-cd377d00-4b64-11ea-81e3-20bdbde76dfe.png)
![2020-02-09-164328_384x142_scrot](https://user-images.githubusercontent.com/1082089/74106201-cdd01380-4b64-11ea-8a2c-6c05a47ef9e4.png)
![2020-02-09-165435_438x431_scrot](https://user-images.githubusercontent.com/1082089/74106202-ce68aa00-4b64-11ea-8195-206938935a92.png)

**Comment by ShinIce** [comment]
I have the same problems as described by @pavlix but on freenode.
Looks like it all was triggered by a netsplit on the 9th feb.

NickServ won't talk to me, only appservice-irc.

**Comment by Half-Shot** [comment]
@ShinIce What's your mxid? I'm having difficulty trying to reproduce this

**Comment by ShinIce** [comment]
@Half-Shot sorry
matrix: @shin.ice:matrix.org
matrix-irc: ShinIce[m]
(if I understood the question right)

**Comment by ShinIce** [comment]
@Half-Shot the update to 0.15.2 fixed, at least, my problem ;)

**Comment by palmer-dabbelt** [comment]
I think I'm getting the same problem on 0.15.2 -- I can match the log from @pavlix exactly, except with my nick (palmer).  I'm @palmer:dabbelt.com, if that helps any.

**Comment by giarve** [comment]
Exactly the same behavior on 0.15.2.

It's been like a week now since I created the account and tried to talk to NickServ (freenode) but the problem is still there.

Is there any way to reset the account without deactivating it so that the NickServ may reply?

**Comment by lboklin** [comment]
Having the same problem, except that after using the `!storepass XXX:XXX` command in a direct chat with `@appservice-irc:matrix.org` NickServ sends me a message saying "XXX is not a registered nickname." and then goes back to not answering my pleading messages.

**Comment by lboklin** [comment]
I figured out the issue in my case. DMs are encrypted by default, so when I `/msg @freenode_NickServ:matrix.org` it invites it to an encrypted direct-message room. It successfully joins it and it will even message me to say things like "XXX is not a registered nickname.", but it will not read or respond to my messages. 

There are no indications that encryption should be an issue, so this is clearly a bug in either UX or behaviour.

**Comment by sk-alexis** [comment]
This issue is happening again @Half-Shot and anybody else, I think though, people are jumping into conclusions here. Because if I would have to guess  and according to my tests, NickServ responds, the problem is the time of response. So people then assume Nickserv is not being contacted. My client took up to 10 hours to respond on some instance, but eventually responded. Don't know why this happens but when equal nicks were present time increased. Cheers.

**Comment by tim-seoss** [comment]
Possible workaround was to temporarily change the IRC nick for the Matrix user (e.g. from `MyNick` to `MyNick_` and then back again to `MyNick`), that seemed to unstick things.
